In [1]:
import pandas as pd 
import pandas as pd
import statsmodels.formula.api as smf
import numpy as np

In [2]:
df_levels_complete = pd.read_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/id_levels_complete.csv')
df_goal_approach_sequencing = pd.read_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/merged_df_final_qual.csv')

In [3]:
df_levels_complete

,ID,levels_complete,len_levels_complete
0,1,"['0level:baba is you', '1level:where do i go?'...",7
1,2,"['0level:baba is you', '1level:where do i go?'...",35
2,3,"['0level:baba is you', '1level:where do i go?'...",8
3,5,"['0level:baba is you', '1level:where do i go?'...",9
4,6,"['0level:baba is you', '1level:where do i go?'...",36
...,...,...,...
180,254,"['0level:baba is you', '1level:where do i go?'...",9
181,255,"['0level:baba is you', '1level:where do i go?'...",23
182,256,"['0level:baba is you', '1level:where do i go?'...",9
183,257,"['236level:changeless', '136level:jelly throne...",19
184,258,"['5level:off limits', '6level:grass yard', '20...",13

In [4]:
df_levels_complete.describe()

               ID  len_levels_complete
count  185.000000           185.000000
mean   143.821622            27.897297
std     75.310990            14.463043
min      1.000000             1.000000
25%     78.000000            18.000000
50%    155.000000            27.000000
75%    209.000000            36.000000
max    258.000000            92.000000

In [5]:
df_goal_approach_sequencing

,Unnamed: 0,ID,out_of_reach,brick_wall,crab_storage,condition_1,condition_2
0,0,6,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
1,1,35,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
2,2,37,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
3,3,38,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
4,4,41,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
...,...,...,...,...,...,...,...
74,74,152,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,d,d2
75,75,176,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,high-returns_fast-reframe_cs,c,c2
76,76,200,high-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,b,b2
77,77,210,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,d,d2
78,78,227,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,d,d2

In [6]:
# print(df_goal_approach_sequencing['approach'].unique())

In [7]:
# # Add new column based on condition
# df_goal_approach_sequencing['approach_condition'] = (df_goal_approach_sequencing['approach']
#                                             .apply(lambda x: 
#                                                    'condition_a' if x == 'low-returns_fast-reframe -> low-returns_fast-reframe -> low-returns_fast-reframe' 
#                                                    else 'condition_b'))

In [8]:
df_goal_approach_sequencing

,Unnamed: 0,ID,out_of_reach,brick_wall,crab_storage,condition_1,condition_2
0,0,6,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
1,1,35,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
2,2,37,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
3,3,38,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
4,4,41,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
...,...,...,...,...,...,...,...
74,74,152,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,d,d2
75,75,176,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,high-returns_fast-reframe_cs,c,c2
76,76,200,high-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,b,b2
77,77,210,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,d,d2
78,78,227,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,d,d2

In [9]:
# combine

In [10]:
df_combined = pd.merge(df_levels_complete, df_goal_approach_sequencing, on='ID', how='inner')

In [11]:
df_combined

,ID,levels_complete,len_levels_complete,Unnamed: 0,out_of_reach,brick_wall,crab_storage,condition_1,condition_2
0,6,"['0level:baba is you', '1level:where do i go?'...",36,0,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
1,12,"['0level:baba is you', '1level:where do i go?'...",37,32,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,d,d1
2,22,"['0level:baba is you', '1level:where do i go?'...",24,43,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,c,c1
3,23,"['0level:baba is you', '1level:where do i go?'...",31,33,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,d,d1
4,26,"['0level:baba is you', '1level:where do i go?'...",38,34,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,d,d1
...,...,...,...,...,...,...,...,...,...
74,241,"['0level:baba is you', '1level:where do i go?'...",34,67,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,b,b1
75,242,"['0level:baba is you', '1level:where do i go?'...",37,52,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,high-returns_fast-reframe_cs,c,c2
76,248,"['0level:baba is you', '1level:where do i go?'...",22,31,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
77,251,"['0level:baba is you', '1level:where do i go?'...",31,63,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,c,c1
78,252,"['0level:baba is you', '1level:where do i go?'...",28,59,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,d,d1

In [12]:
df_combined.to_csv('/Users/baselhussein/Downloads/testing.csv')

In [12]:
df_stats_id = df_combined[['ID', 'len_levels_complete', 'condition_1', 'condition_2']]

In [13]:
df_stats = df_combined[['len_levels_complete', 'condition_1', 'condition_2']]

In [14]:
df_stats

    len_levels_complete condition_1 condition_2
0                    36           a           a
1                    37           d          d1
2                    24           c          c1
3                    31           d          d1
4                    38           d          d1
..                  ...         ...         ...
74                   34           b          b1
75                   37           c          c2
76                   22           a           a
77                   31           c          c1
78                   28           d          d1

[79 rows x 3 columns]

In [15]:
# def remove_outliers(df_stats, threshold=3):
#     """
#     Remove outliers that are more than `threshold` standard deviations from the mean.
#     """
#     for column in df_stats.columns:
#         mean = df_stats[column].mean()
#         std = df_stats[column].std()
#         lower_bound, upper_bound = mean - threshold * std, mean + threshold * std
#         df_stats = df_stats[(df_stats[column] >= lower_bound) & (df_stats[column] <= upper_bound)]
#     return df_stats

In [16]:
# df_stats_no_outliers = remove_outliers(df_stats)

In [17]:
df_stats.describe()

       len_levels_complete
count            79.000000
mean             37.316456
std              12.113295
min              20.000000
25%              29.500000
50%              36.000000
75%              41.500000
max              92.000000

In [18]:
df_stats

    len_levels_complete condition_1 condition_2
0                    36           a           a
1                    37           d          d1
2                    24           c          c1
3                    31           d          d1
4                    38           d          d1
..                  ...         ...         ...
74                   34           b          b1
75                   37           c          c2
76                   22           a           a
77                   31           c          c1
78                   28           d          d1

[79 rows x 3 columns]

In [19]:
average_by_condition = df_stats.groupby('condition_1')['len_levels_complete'].mean()
average_by_condition

condition_1
a    42.187500
b    33.900000
c    34.411765
d    33.700000
Name: len_levels_complete, dtype: float64

In [20]:
df_stats.groupby('condition_1')['len_levels_complete'].count()

condition_1
a    32
b    10
c    17
d    20
Name: len_levels_complete, dtype: int64

In [21]:
average_by_condition_2 = df_stats.groupby('condition_2')['len_levels_complete'].mean()
average_by_condition_2

condition_2
a     42.187500
b1    33.857143
b2    34.000000
c1    31.000000
c2    39.285714
d1    33.812500
d2    33.250000
Name: len_levels_complete, dtype: float64

In [22]:
df_stats.groupby('condition_2')['len_levels_complete'].count()

condition_2
a     32
b1     7
b2     3
c1    10
c2     7
d1    16
d2     4
Name: len_levels_complete, dtype: int64

In [23]:
# condition_a = df_stats[df_stats['approach_condition'] == 'condition_a']['len_levels_complete']
# condition_b = df_stats[df_stats['approach_condition'] == 'condition_b']['len_levels_complete']

In [25]:
# type(condition_a)

In [ ]:
len(condition_a)#

In [ ]:
len(condition_b)

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

# Histogram
plt.hist(condition_a, bins=20, alpha=0.7, color='blue')
plt.title('Histogram')
plt.show()

# Q-Q plot
stats.probplot(condition_a, dist="norm", plot=plt)
plt.title('Q-Q Plot')
plt.show()

# Shapiro-Wilk test
shapiro_stat, shapiro_p = stats.shapiro(condition_a)
print(f"Shapiro-Wilk Test: Stat={shapiro_stat}, P-value={shapiro_p}")

# Kolmogorov-Smirnov test (comparing against a normal distribution)
ks_stat, ks_p = stats.kstest(condition_a, 'norm', args=(condition_a.mean(), condition_a.std()))
print(f"Kolmogorov-Smirnov Test: Stat={ks_stat}, P-value={ks_p}")

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

# Histogram
plt.hist(condition_b, bins=20, alpha=0.7, color='blue')
plt.title('Histogram')
plt.show()

# Q-Q plot
stats.probplot(condition_b, dist="norm", plot=plt)
plt.title('Q-Q Plot')
plt.show()

# Shapiro-Wilk test
shapiro_stat, shapiro_p = stats.shapiro(condition_b)
print(f"Shapiro-Wilk Test: Stat={shapiro_stat}, P-value={shapiro_p}")

# Kolmogorov-Smirnov test (comparing against a normal distribution)
ks_stat, ks_p = stats.kstest(condition_b, 'norm', args=(condition_b.mean(), condition_b.std()))
print(f"Kolmogorov-Smirnov Test: Stat={ks_stat}, P-value={ks_p}")

In [ ]:
# condition_a

In [ ]:
from scipy.stats import ttest_ind

In [ ]:
import numpy as np
from scipy.stats import ttest_ind, levene
from statsmodels.stats.weightstats import DescrStatsW
from math import sqrt

# Function to remove outliers
def remove_outliers(data):
    mean = data.mean()
    std_dev = data.std()
    return data[(data > mean - 3 * std_dev) & (data < mean + 3 * std_dev)]

# Remove outliers from both conditions
condition_a_clean = remove_outliers(condition_a)
condition_b_clean = remove_outliers(condition_b)

# Perform Levene's test for equality of variances
levene_stat, levene_p = levene(condition_a_clean, condition_b_clean)
print(f"Levene's test statistic: {levene_stat}")
print(f"Levene's test p-value: {levene_p}")

# Perform independent t-test
t_stat, p_value = ttest_ind(condition_a_clean, condition_b_clean, equal_var=(levene_p >= 0.05))

print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

# Interpret the p-value
alpha = 0.05

if p_value < alpha:
    print("The difference between the two conditions is statistically significant.")
else:
    print("The difference between the two conditions is not statistically significant.")

# Calculate mean difference
mean_diff = np.mean(condition_a_clean) - np.mean(condition_b_clean)
print(f"Mean difference: {mean_diff}")

# Calculate pooled standard deviation for Cohen's d
n_a = len(condition_a_clean)
n_b = len(condition_b_clean)
std_a = np.std(condition_a_clean, ddof=1)
std_b = np.std(condition_b_clean, ddof=1)
pooled_std = sqrt(((n_a - 1) * std_a**2 + (n_b - 1) * std_b**2) / (n_a + n_b - 2))

# Calculate Cohen's d
cohen_d = mean_diff / pooled_std
print(f"Cohen's d: {cohen_d}")

# Calculate confidence interval for the mean difference
data_a = DescrStatsW(condition_a_clean)
data_b = DescrStatsW(condition_b_clean)
cm = data_a.get_compare(data_b)
ci_low, ci_high = cm.tconfint_diff(usevar='pooled')
print(f"95% confidence interval for the mean difference: ({ci_low}, {ci_high})")

In [ ]:
# # Function to remove outliers
# # def remove_outliers(data):
# #     mean = data.mean()
# #     std_dev = data.std()
# #     return data[(data > mean - 3 * std_dev) & (data < mean + 3 * std_dev)]

# # # Remove outliers from both conditions
# # condition_a_clean = remove_outliers(condition_a)
# # condition_b_clean = remove_outliers(condition_b)

# # Perform independent t-test
# t_stat, p_value = ttest_ind(condition_a, condition_b)

# print(f"T-statistic: {t_stat}")
# print(f"P-value: {p_value}")

# # Interpret the p-value
# alpha = 0.05

# if p_value < alpha:
#     print("The difference between the two conditions is statistically significant.")
    
# else:
#     print("The difference between the two conditions is not statistically significant.")

In [ ]:
condition_a.mean()

In [ ]:
condition_b.mean()

In [ ]:
# Mann-Whitney U test
u_stat, p_value = stats.mannwhitneyu(condition_a_clean, condition_b_clean, alternative='two-sided')

print(f"Mann-Whitney U Test: U-statistic={u_stat}, P-value={p_value}")

In [ ]:
# df_stats_id.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/df_stats_id.csv')

In [ ]:
# Update the reference category for condition_1
df_stats_id['condition_1'] = df_stats_id['condition_1'].astype('category')
df_stats_id['condition_1'] = df_stats_id['condition_1'].cat.reorder_categories(['a'] + [c for c in df_stats_id['condition_1'].unique() if c != 'a'])

In [ ]:
df_stats_id

In [ ]:
# Fit the model with condition_1 as the fixed effect and `a` as the reference
model_fixed_effects_condition_1 = smf.mixedlm("len_levels_complete ~ condition_1", df_stats_id, groups=df_stats_id["ID"])
result_fixed_effects_condition_1 = model_fixed_effects_condition_1.fit()

# Display the model summary
result_fixed_effects_condition_1_summary = result_fixed_effects_condition_1.summary()
result_fixed_effects_condition_1_summary