In [164]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

In [165]:
df_oor = pd.read_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/oor_clusters.csv')
df_bw = pd.read_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/bw_clusters.csv')
df_cs = pd.read_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/cs_clusters.csv')
df_qual = pd.read_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/transition_counts-qual.csv')

In [166]:
df_qual

,out_of_reach,brick_wall,crab_storage,count,multilevel_1,multilevel_2
0,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,32,a,a
1,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,4,b,b1
2,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,3,b,b1
3,low-returns_slow-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,2,b,b2
4,high-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,1,b,b2
5,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,6,c,c1
6,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,4,c,c1
7,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,high-returns_fast-reframe_cs,4,c,c2
8,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_slow-reframe_cs,2,c,c2
9,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,high-returns_fast-reframe_cs,1,c,c2
10,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,11,d,d1
11,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,5,d,d1
12,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,1,d,d2
13,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,1,d,d2
14,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,1,d,d2
15,low-returns_slow-reframe_oor,low-returns_slow-reframe_bw,high-returns_fast-reframe_cs,1,d,d2

In [167]:
df_qual.drop(['count'], axis=1, inplace=True)

In [168]:
df_qual.columns = ['cluster-category-oor', 'cluster-category-bw', 'cluster-category-cs', 'condition_1', 'condition_2']

In [169]:
df_qual

,cluster-category-oor,cluster-category-bw,cluster-category-cs,condition_1,condition_2
0,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,a,a
1,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,b,b1
2,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,b,b1
3,low-returns_slow-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,b,b2
4,high-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,b,b2
5,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,c,c1
6,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,c,c1
7,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,high-returns_fast-reframe_cs,c,c2
8,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_slow-reframe_cs,c,c2
9,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,high-returns_fast-reframe_cs,c,c2
10,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,d,d1
11,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,d,d1
12,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,d,d2
13,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,d,d2
14,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,d,d2
15,low-returns_slow-reframe_oor,low-returns_slow-reframe_bw,high-returns_fast-reframe_cs,d,d2

In [170]:
df_qual['cluster-category-oor'] = df_qual['cluster-category-oor'].str.replace('_oor', '', regex=False)
df_qual['cluster-category-bw'] = df_qual['cluster-category-bw'].str.replace('_bw', '', regex=False)
df_qual['cluster-category-cs'] = df_qual['cluster-category-cs'].str.replace('_cs', '', regex=False)

In [171]:
df_bw_clean = df_bw[['ID', 'cluster-category-bw']]
df_bw_clean

      ID        cluster-category-bw
0      2   low-returns_fast-reframe
1      6   low-returns_fast-reframe
2     12   low-returns_slow-reframe
3     13   low-returns_fast-reframe
4     22   low-returns_fast-reframe
..   ...                        ...
126  248   low-returns_fast-reframe
127  251   low-returns_fast-reframe
128  252  high-returns_fast-reframe
129  255  high-returns_fast-reframe
130  257  high-returns_fast-reframe

[131 rows x 2 columns]

In [172]:
df_cs_clean = df_cs[['ID', 'cluster-category-cs']]
df_cs_clean

     ID        cluster-category-cs
0     6   low-returns_fast-reframe
1    12   low-returns_fast-reframe
2    22  high-returns_fast-reframe
3    23   low-returns_fast-reframe
4    26   low-returns_fast-reframe
..  ...                        ...
85  242  high-returns_fast-reframe
86  245   low-returns_slow-reframe
87  248   low-returns_fast-reframe
88  251   low-returns_slow-reframe
89  252   low-returns_fast-reframe

[90 rows x 2 columns]

In [173]:
df_oor_clean = df_oor[['ID', 'cluster-category-oor']]
df_oor_clean

      ID      cluster-category-oor
0      1  low-returns_slow-reframe
1      2  low-returns_fast-reframe
2      3  low-returns_fast-reframe
3      5  low-returns_slow-reframe
4      6  low-returns_fast-reframe
..   ...                       ...
166  253  low-returns_fast-reframe
167  254  low-returns_fast-reframe
168  255  low-returns_fast-reframe
169  256  low-returns_fast-reframe
170  257  low-returns_fast-reframe

[171 rows x 2 columns]

In [174]:
merged_df = pd.merge(df_oor_clean, df_bw_clean, on='ID', how='inner')
merged_df

      ID      cluster-category-oor        cluster-category-bw
0      2  low-returns_fast-reframe   low-returns_fast-reframe
1      6  low-returns_fast-reframe   low-returns_fast-reframe
2     12  low-returns_fast-reframe   low-returns_slow-reframe
3     13  low-returns_fast-reframe   low-returns_fast-reframe
4     22  low-returns_fast-reframe   low-returns_fast-reframe
..   ...                       ...                        ...
121  248  low-returns_fast-reframe   low-returns_fast-reframe
122  251  low-returns_fast-reframe   low-returns_fast-reframe
123  252  low-returns_fast-reframe  high-returns_fast-reframe
124  255  low-returns_fast-reframe  high-returns_fast-reframe
125  257  low-returns_fast-reframe  high-returns_fast-reframe

[126 rows x 3 columns]

In [175]:
merged_df_final = pd.merge(merged_df, df_cs_clean, on='ID', how='inner')
merged_df_final

,ID,cluster-category-oor,cluster-category-bw,cluster-category-cs
0,6,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe
1,12,low-returns_fast-reframe,low-returns_slow-reframe,low-returns_fast-reframe
2,22,low-returns_fast-reframe,low-returns_fast-reframe,high-returns_fast-reframe
3,23,low-returns_fast-reframe,low-returns_slow-reframe,low-returns_fast-reframe
4,26,low-returns_fast-reframe,low-returns_slow-reframe,low-returns_fast-reframe
...,...,...,...,...
74,241,high-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe
75,242,low-returns_fast-reframe,low-returns_slow-reframe,high-returns_fast-reframe
76,248,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe
77,251,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_slow-reframe
78,252,low-returns_fast-reframe,high-returns_fast-reframe,low-returns_fast-reframe

In [176]:
df_qual

,cluster-category-oor,cluster-category-bw,cluster-category-cs,condition_1,condition_2
0,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe,a,a
1,high-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe,b,b1
2,low-returns_slow-reframe,low-returns_fast-reframe,low-returns_fast-reframe,b,b1
3,low-returns_slow-reframe,low-returns_slow-reframe,low-returns_fast-reframe,b,b2
4,high-returns_fast-reframe,high-returns_fast-reframe,low-returns_fast-reframe,b,b2
5,low-returns_fast-reframe,low-returns_fast-reframe,high-returns_fast-reframe,c,c1
6,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_slow-reframe,c,c1
7,low-returns_fast-reframe,low-returns_slow-reframe,high-returns_fast-reframe,c,c2
8,low-returns_fast-reframe,low-returns_slow-reframe,low-returns_slow-reframe,c,c2
9,low-returns_fast-reframe,high-returns_fast-reframe,high-returns_fast-reframe,c,c2
10,low-returns_fast-reframe,low-returns_slow-reframe,low-returns_fast-reframe,d,d1
11,low-returns_fast-reframe,high-returns_fast-reframe,low-returns_fast-reframe,d,d1
12,high-returns_fast-reframe,low-returns_fast-reframe,high-returns_fast-reframe,d,d2
13,low-returns_slow-reframe,low-returns_fast-reframe,high-returns_fast-reframe,d,d2
14,low-returns_slow-reframe,low-returns_fast-reframe,low-returns_slow-reframe,d,d2
15,low-returns_slow-reframe,low-returns_slow-reframe,high-returns_fast-reframe,d,d2

In [177]:
# Clean the cluster-category columns in both DataFrames
for col in ['cluster-category-oor', 'cluster-category-bw', 'cluster-category-cs']:
    merged_df_final[col] = merged_df_final[col].str.strip().str.lower()
    df_qual[col] = df_qual[col].str.strip().str.lower()

In [178]:
merged_df_final_qual = pd.merge(merged_df_final, df_qual, on=['cluster-category-oor', 'cluster-category-bw', 'cluster-category-cs'], how='inner')

In [179]:
merged_df_final_qual

,ID,cluster-category-oor,cluster-category-bw,cluster-category-cs,condition_1,condition_2
0,6,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe,a,a
1,35,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe,a,a
2,37,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe,a,a
3,38,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe,a,a
4,41,low-returns_fast-reframe,low-returns_fast-reframe,low-returns_fast-reframe,a,a
...,...,...,...,...,...,...
74,152,low-returns_slow-reframe,low-returns_fast-reframe,low-returns_slow-reframe,d,d2
75,176,low-returns_fast-reframe,high-returns_fast-reframe,high-returns_fast-reframe,c,c2
76,200,high-returns_fast-reframe,high-returns_fast-reframe,low-returns_fast-reframe,b,b2
77,210,high-returns_fast-reframe,low-returns_fast-reframe,high-returns_fast-reframe,d,d2
78,227,low-returns_slow-reframe,low-returns_fast-reframe,high-returns_fast-reframe,d,d2

In [180]:
merged_df_final_qual.rename(columns={
    'cluster-category-oor': 'out_of_reach',
    'cluster-category-bw': 'brick_wall',
    'cluster-category-cs': 'crab_storage'
}, inplace=True)

In [181]:
merged_df_final_approach = pd.DataFrame(merged_df_final_qual['ID'])
merged_df_final_approach

     ID
0     6
1    35
2    37
3    38
4    41
..  ...
74  152
75  176
76  200
77  210
78  227

[79 rows x 1 columns]

In [182]:
merged_df_final_approach['approach'] = (merged_df_final_qual['out_of_reach'] + " -> " + 
                              merged_df_final_qual['brick_wall'] + " -> " + 
                              merged_df_final_qual['crab_storage']
                              )

In [183]:
# ids_evaluation = merged_df_final_approach['ID']

In [184]:
merged_df_final_approach

     ID                                           approach
0     6  low-returns_fast-reframe -> low-returns_fast-r...
1    35  low-returns_fast-reframe -> low-returns_fast-r...
2    37  low-returns_fast-reframe -> low-returns_fast-r...
3    38  low-returns_fast-reframe -> low-returns_fast-r...
4    41  low-returns_fast-reframe -> low-returns_fast-r...
..  ...                                                ...
74  152  low-returns_slow-reframe -> low-returns_fast-r...
75  176  low-returns_fast-reframe -> high-returns_fast-...
76  200  high-returns_fast-reframe -> high-returns_fast...
77  210  high-returns_fast-reframe -> low-returns_fast-...
78  227  low-returns_slow-reframe -> low-returns_fast-r...

[79 rows x 2 columns]

In [185]:
# Create a new DataFrame by copying the original
df_numbers = merged_df_final.copy()

# Replace values in the new DataFrame
df_numbers.replace('low-returns_fast-reframe', 1, inplace=True)
df_numbers.replace('low-returns_slow-reframe', 2, inplace=True)
df_numbers.replace('high-returns_fast-reframe', 3, inplace=True)

In [186]:
df_numbers

     ID  cluster-category-oor  cluster-category-bw  cluster-category-cs
0     6                     1                    1                    1
1    12                     1                    2                    1
2    22                     1                    1                    3
3    23                     1                    2                    1
4    26                     1                    2                    1
..  ...                   ...                  ...                  ...
74  241                     3                    1                    1
75  242                     1                    2                    3
76  248                     1                    1                    1
77  251                     1                    1                    2
78  252                     1                    3                    1

[79 rows x 4 columns]

In [187]:
merged_df_final_qual['out_of_reach'] = merged_df_final_qual['out_of_reach'] + "_oor"
merged_df_final_qual['brick_wall'] = merged_df_final_qual['brick_wall'] + "_bw"
merged_df_final_qual['crab_storage'] = merged_df_final_qual['crab_storage'] + "_cs"

In [188]:
df_numeric = df_numbers.drop(columns=['ID'])
# df_numeric

In [189]:
# # Compare the two columns and create a boolean series
# same_values = df_numbers['out_of_reach'] == df_numbers['brick_wall'] == df_numbers['crab_storage']

# # Calculate the number of matching rows
# num_matches = same_values.sum()

# # Calculate the proportion of matching rows
# proportion_matches = same_values.mean()

# print(f"Proportion of rows where levels are the same: {proportion_matches:.2f}")

In [190]:
transition_counts = merged_df_final_qual.groupby(['out_of_reach', 'brick_wall', 'crab_storage']).agg(
    count=('ID', 'size'),
    ID_list=('ID', lambda x: list(x))
).reset_index()

In [191]:
transition_counts

,out_of_reach,brick_wall,crab_storage,count,ID_list
0,high-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,1,[200]
1,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,1,[210]
2,high-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,4,"[90, 194, 202, 241]"
3,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,high-returns_fast-reframe_cs,1,[176]
4,low-returns_fast-reframe_oor,high-returns_fast-reframe_bw,low-returns_fast-reframe_cs,5,"[76, 151, 181, 208, 252]"
5,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,6,"[22, 74, 143, 156, 183, 220]"
6,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,32,"[6, 35, 37, 38, 41, 62, 70, 73, 80, 91, 105, 1..."
7,low-returns_fast-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,4,"[83, 136, 192, 251]"
8,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,high-returns_fast-reframe_cs,4,"[42, 46, 205, 242]"
9,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,11,"[12, 23, 26, 53, 67, 71, 123, 184, 215, 225, 237]"
10,low-returns_fast-reframe_oor,low-returns_slow-reframe_bw,low-returns_slow-reframe_cs,2,"[121, 236]"
11,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,high-returns_fast-reframe_cs,1,[227]
12,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_fast-reframe_cs,3,"[117, 166, 235]"
13,low-returns_slow-reframe_oor,low-returns_fast-reframe_bw,low-returns_slow-reframe_cs,1,[152]
14,low-returns_slow-reframe_oor,low-returns_slow-reframe_bw,high-returns_fast-reframe_cs,1,[100]
15,low-returns_slow-reframe_oor,low-returns_slow-reframe_bw,low-returns_fast-reframe_cs,2,"[63, 147]"

In [192]:
transitions_oor_bw = merged_df_final_qual.groupby(['out_of_reach', 'brick_wall']).size().reset_index(name='count')

In [193]:
transitions_oor_bw

                    out_of_reach                    brick_wall  count
0  high-returns_fast-reframe_oor  high-returns_fast-reframe_bw      1
1  high-returns_fast-reframe_oor   low-returns_fast-reframe_bw      5
2   low-returns_fast-reframe_oor  high-returns_fast-reframe_bw      6
3   low-returns_fast-reframe_oor   low-returns_fast-reframe_bw     42
4   low-returns_fast-reframe_oor   low-returns_slow-reframe_bw     17
5   low-returns_slow-reframe_oor   low-returns_fast-reframe_bw      5
6   low-returns_slow-reframe_oor   low-returns_slow-reframe_bw      3

In [194]:
transitions_bw_cs = merged_df_final_qual.groupby(['brick_wall', 'crab_storage']).size().reset_index(name='count')
transitions_bw_cs

                     brick_wall                  crab_storage  count
0  high-returns_fast-reframe_bw  high-returns_fast-reframe_cs      1
1  high-returns_fast-reframe_bw   low-returns_fast-reframe_cs      6
2   low-returns_fast-reframe_bw  high-returns_fast-reframe_cs      8
3   low-returns_fast-reframe_bw   low-returns_fast-reframe_cs     39
4   low-returns_fast-reframe_bw   low-returns_slow-reframe_cs      5
5   low-returns_slow-reframe_bw  high-returns_fast-reframe_cs      5
6   low-returns_slow-reframe_bw   low-returns_fast-reframe_cs     13
7   low-returns_slow-reframe_bw   low-returns_slow-reframe_cs      2

In [195]:
# transition_counts["brick_wall"] = transition_counts["brick_wall"] + "_bw"
# transition_counts

In [196]:
### Export + Spot Check

In [197]:
merged_df.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/clusters_labelled.csv', index=False)
df_numbers.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/clusters_labelled_numbers.csv', index=False)
transition_counts.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/transition_counts.csv', index=False)
transitions_oor_bw.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/transitions_oor_bw.csv', index=False)
transitions_bw_cs.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/transitions_bw_cs.csv', index=False)
merged_df_final_approach.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/goal_approach_levels.csv', index=False)
# ids_evaluation.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/ids_evaluation.csv')
merged_df_final_qual.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/merged_df_final_qual.csv')