### README

In [6]:
# TODO

### Import Packages

In [17]:
import pandas as pd
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score, davies_bouldin_score

### Import Data

In [10]:
df = pd.read_csv('/Users/baselhussein/Projects/impossible_goals/data/cluster_features.csv')
df

      ID  unique_goals  total_returns  seconds_to_first_goal_switch
0      2             3              4                        13.416
1      6             3              0                         8.816
2     12             8             22                        17.533
3     13             7              8                         9.300
4     22             3              0                        15.067
..   ...           ...            ...                           ...
145  252             8             35                        14.133
146  253             8             63                        10.450
147  255             7             38                         8.283
148  257             6             36                        25.350
149  258             7            104                         9.600

[150 rows x 4 columns]

### Preprocessing

In [33]:
# Drop ID column if it's not needed for clustering
data = df.drop('ID', axis=1)

# Preprocessing: Scale the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

# Choose the number of clusters (K)
k = 7

# Initialize KMeans clustering algorithm
kmeans = KMeans(n_clusters=k, random_state=42)

# Fit the KMeans model to the scaled data
kmeans.fit(scaled_data)

# Get the cluster labels
cluster_labels = kmeans.labels_

# Add cluster labels to the DataFrame
df['Cluster'] = cluster_labels

/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

In [34]:
df

      ID  unique_goals  total_returns  seconds_to_first_goal_switch  Cluster
0      2             3              4                        13.416        1
1      6             3              0                         8.816        6
2     12             8             22                        17.533        5
3     13             7              8                         9.300        0
4     22             3              0                        15.067        1
..   ...           ...            ...                           ...      ...
145  252             8             35                        14.133        2
146  253             8             63                        10.450        2
147  255             7             38                         8.283        2
148  257             6             36                        25.350        5
149  258             7            104                         9.600        4

[150 rows x 5 columns]

### Visualization

In [35]:
# Visualize the clusters
fig = px.scatter_matrix(df, color='Cluster', title='Clustering Visualization')
fig.update_traces(diagonal_visible=False)  # Hide histograms on the diagonal
fig.show()

AttributeError: 'DataFrame' object has no attribute 'iteritems'

### Evaluation

In [36]:
# Evaluate the clustering
silhouette = silhouette_score(scaled_data, cluster_labels)
db_index = davies_bouldin_score(scaled_data, cluster_labels)

print(f"Silhouette Score: {silhouette}")
print(f"Davies-Bouldin Index: {db_index}")

Silhouette Score: 0.45942534603886204
Davies-Bouldin Index: 0.8558429746437105

In [38]:
# Define range of k values
k_values = range(2, 15)  # Adjust range as needed

# Store silhouette scores
silhouette_scores = []

for k in k_values:
    # Initialize KMeans clustering algorithm
    kmeans = KMeans(n_clusters=k, random_state=42)
    
    # Fit the KMeans model to the scaled data
    kmeans.fit(scaled_data)
    
    # Get the cluster labels
    cluster_labels = kmeans.labels_
    
    # Calculate silhouette score
    silhouette = silhouette_score(scaled_data, cluster_labels)
    silhouette_scores.append(silhouette)

# Print summary of silhouette scores
print("Silhouette Scores:")
for k, score in zip(k_values, silhouette_scores):
    print(f"Number of Clusters (k = {k}): Silhouette Score = {score}")

/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

Silhouette Scores:
Number of Clusters (k = 2): Silhouette Score = 0.35677411879613735
Number of Clusters (k = 3): Silhouette Score = 0.4180767484593502
Number of Clusters (k = 4): Silhouette Score = 0.5239056590050424
Number of Clusters (k = 5): Silhouette Score = 0.5287982791379662
Number of Clusters (k = 6): Silhouette Score = 0.5463621283174908
Number of Clusters (k = 7): Silhouette Score = 0.45942534603886204
Number of Clusters (k = 8): Silhouette Score = 0.4528823093701009
Number of Clusters (k = 9): Silhouette Score = 0.42619315972119365
Number of Clusters (k = 10): Silhouette Score = 0.4274670348699983
Number of Clusters (k = 11): Silhouette Score = 0.3599476093409152
Number of Clusters (k = 12): Silhouette Score = 0.36872044904109347
Number of Clusters (k = 13): Silhouette Score = 0.3670615033147275
Number of Clusters (k = 14): Silhouette Score = 0.3754237235014152

/Users/baselhussein/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)